# Generated by Django 4.1.5 on 2023-01-24 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aws_backup_and_restore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup_s3',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='aws_backup_and_restore.projectdatabase'),
        ),
        migrations.AlterField(
            model_name='buckets',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='aws_backup_and_restore.projectdatabase'),
        ),
    ]
