# Generated by Django 4.1.5 on 2023-01-24 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws_backup_and_restore', '0002_alter_backup_s3_project_alter_buckets_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Backup_s3',
            new_name='BackupS3',
        ),
    ]
