# Generated by Django 4.1.5 on 2023-01-24 03:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aws_backup_and_restore', '0003_rename_backup_s3_backups3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdatabase',
            name='uuid',
        ),
        migrations.AddField(
            model_name='projectdatabase',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
