# Generated by Django 4.1.5 on 2023-01-24 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws_backup_and_restore', '0004_remove_projectdatabase_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdatabase',
            name='unique_id',
        ),
    ]
