# Generated by Django 4.1.5 on 2023-01-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_backup_and_restore', '0006_projectdatabase_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdatabase',
            name='unique_id',
            field=models.CharField(default='test', max_length=200),
        ),
    ]
