# Generated by Django 4.1.5 on 2023-01-24 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws_backup_and_restore', '0007_alter_projectdatabase_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdatabase',
            name='unique_id',
        ),
    ]
